Implement Netflix Clone
dhairyagothi/100_days_100_web_project pull request #129
Opened 2024-06-20 14:28 UTC by Yaser-123

The goal of this project is to create a functional clone of the Netflix platform. This clone should mimic the core features of Netflix, including user authentication, browsing of movie/TV show catalogs, streaming video content, and user-specific recommendations.

Key Features:
1.Header Section
2.Hero Section
3.Content Sections
4.Footer Section

Technical Stack:
1.Frontend
2.Responsive Design
3.Consistent Theme

Additional Notes:
Collaborate with the design team to ensure visual fidelity.
Ensure cross-browser compatibility (Chrome, Firefox, Safari, Edge).
Solicit feedback from team members and potential users to refine the design.

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/aa70757c-1047-4a1b-ba83-2fddc20d58c9

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/fb63ee10-6ebe-4a6f-ba74-ddb8cdcc8f0d

2024-06-20 14:47 UTC, Yaser-123 commented
Issue #102

2024-06-20 16:41 UTC, dhairyagothi requested changes

2024-06-20 16:41 UTC, dhairyagothi commented on public/index.html
>              <a href="Amazon_Clone/index.html" class="demo-link">Demo</a>
fix this 
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/8e98a2bf-ffe4-48ce-af8a-6c8bc9d9b007)

pull main branch first

2024-06-20 17:01 UTC, dhairyagothi commented on public/index.html
>              <a href="Amazon_Clone/index.html" class="demo-link">Demo</a>
@Yaser-123

2024-06-20 18:24 UTC, dhairyagothi commented
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/405a2711-3d30-4434-af1d-4b4f1ab3a904)

resolve this

2024-06-21 10:41 UTC, Yaser-123 commented
Done bro resolved pr it

2024-06-21 12:52 UTC, merged

2026-06-17 09:05 UTC, anshul23102 commented
Closing - being refiled with proper detailed professional template per framework standards.