Unit Tests for Climate Data Parsing Module
dhairyagothi/100_days_100_web_project pull request #139
Opened 2024-06-21 15:52 UTC by Yaser-123

Description:
We need to improve the reliability and robustness of our climate data parsing module by adding comprehensive unit tests. This will ensure that the module correctly parses various climate data formats and handles edge cases gracefully.
Tasks:
1.Set Up Testing Framework
2.Identify Key Functions for Testing
3.Write Unit Tests
4.Run and Verify Tests

Issue #131 

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/07e4104c-f11d-44fe-977a-2b1f244354f6

https://github.com/dhairyagothi/50_days_50_web_project/assets/140265777/79fe2fd6-2537-451d-bb9a-94b7414b0684

2024-06-22 05:51 UTC, dhairyagothi requested changes

2024-06-22 05:51 UTC, dhairyagothi commented on public/index.html
> +            <div class="project-name">ClimaCode</div>
i recently merged a PR you add it as 52 
![Uploading image.png…]()

2024-06-22 05:51 UTC, dhairyagothi commented on public/index.html
> +            <div class="project-name">ClimaCode</div>
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/8eb076fb-887f-4da3-9252-7d30560c8bf7)

2024-06-23 04:45 UTC, Yaser-123 commented
Done changed as 52

2024-06-23 06:14 UTC, dhairyagothi commented
always add email id yrr
dont remove PR format while making PR

2024-06-23 06:38 UTC, Yaser-123 commented
Email :- 1ammar.yaser@gmail.com

2024-06-23 07:43 UTC, merged