Spotify clone  project added
dhairyagothi/100_days_100_web_project pull request #221
Opened 2024-07-05 10:23 UTC by bhagwan8815

## Related Issue
 i am add a new project in your Repository which is Spotify Clone Project.
issue no.  :  #219  

## Email id used to regsiter for VSoc'24
Email id:     ranabhagwan8815@gmail.com

## Type of PR

- [ ] Bug fix
- [ x] Feature enhancement
- [ x] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/7f7bcbf5-041f-4f0c-8e63-0437a62f6141

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x ] I have performed a self-review of my code.
- [x ] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have followed the code style guidelines of this project.
- [ x] I have checked for any existing open issues that my pull request may address.
- [ x] I have ensured that my changes do not break any existing functionality.
- [ x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ x] I have read the resources for guidance listed below.
- [ x] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

2024-07-06 11:27 UTC, dhairyagothi requested changes
update index.html after doing sync fork and pull

2024-07-06 12:51 UTC, bhagwan8815 commented
update file index.html pls check

2024-07-06 14:35 UTC, dhairyagothi commented
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/b302dd26-4edb-4a84-b262-38c15bf67564)
@bhagwan8815 
sync fork thrn pull main branch then do edit

2024-07-06 15:46 UTC, bhagwan8815 commented
update file index.html pls check

2024-07-06 16:37 UTC, dhairyagothi requested changes

2024-07-06 16:37 UTC, dhairyagothi commented on public/index.html
> -        <div class="table">
sync Fork and then edit it

2024-07-06 16:39 UTC, dhairyagothi requested changes

2024-07-06 16:39 UTC, dhairyagothi commented on public/index.html
> +            <a href="public/spotify-clone -project/index.html" class="demo-link">Demo</a>
check href public/spotify-clone -project/index.html

2024-07-06 19:41 UTC, dhairyagothi requested changes
before 
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/990f1b7e-fb06-4477-b411-19a3687b8dc2)

your PR
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/77bb2833-4ebc-4f48-afa3-c4d0e4c5d382)


![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/382fd05c-c62e-4c9f-8054-04fd69b131e2)

dont do like this 

sync fork then edit already told you

2024-07-06 19:44 UTC, dhairyagothi requested changes

2024-07-06 19:44 UTC, dhairyagothi commented on public/index.html
> +            <a href="https://github.com/bhagwan8815/Rana_repo/blob/spotify-clone/public/spotify-clone%20-project/index.html" class="demo-link">Demo</a>
add  
```html 
href="./public/spotify-clone-project/index.html" 
```

2024-07-07 03:07 UTC, bhagwan8815 commented on public/index.html
> +            <a href="https://github.com/bhagwan8815/Rana_repo/blob/spotify-clone/public/spotify-clone%20-project/index.html" class="demo-link">Demo</a>
bhai 
  href="./public/spotify-clone-project/index.html"       
  ye link add karna he kya ???

2024-07-07 07:57 UTC, bhagwan8815 commented on public/index.html
> +            <a href="https://github.com/bhagwan8815/Rana_repo/blob/spotify-clone/public/spotify-clone%20-project/index.html" class="demo-link">Demo</a>
Bhai konsi link add karna he ye bata do pls.

2024-07-07 09:20 UTC, dhairyagothi commented on public/index.html
> +            <a href="https://github.com/bhagwan8815/Rana_repo/blob/spotify-clone/public/spotify-clone%20-project/index.html" class="demo-link">Demo</a>
index.html m repo ki link mat daalo ye daalo

2024-07-07 10:05 UTC, bhagwan8815 commented on public/index.html
> +            <a href="https://github.com/bhagwan8815/Rana_repo/blob/spotify-clone/public/spotify-clone%20-project/index.html" class="demo-link">Demo</a>
Ok bhai

2024-07-07 11:22 UTC, dhairyagothi commented
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/27ad0deb-e6fc-41c1-a888-53f4288eca55)


@bhagwan8815 dusri links remove kar di tumne

2024-07-07 11:23 UTC, bhagwan8815 commented
Nahi bhai saari hi he

2024-07-07 11:25 UTC, dhairyagothi requested changes

2024-07-07 11:25 UTC, dhairyagothi commented on public/index.html
> -            <div class="day-number">Day 67</div>
day 66 67 68 missing h

2024-07-07 11:26 UTC, bhagwan8815 commented
Mene Jo Repository frok ki he usme saari hi dikha raha h

2024-07-07 11:28 UTC, dhairyagothi commented
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/65f03f85-1ffa-4457-b347-01255289314b)

@bhagwan8815  dont create multiiple branches 
do changes in main branch then push spotify clone branch m nhi h dusre days ki link

2024-07-07 11:53 UTC, bhagwan8815 commented
Bhai kar diya, pls check karo

2024-07-07 15:10 UTC, dhairyagothi approved these changes

2024-07-07 15:15 UTC, merged