Footer_small the icons of contributors
dhairyagothi/100_days_100_web_project pull request #244
Opened 2024-07-08 19:53 UTC by DavidMarcosJ

Footer added, with contributor icons and social icons.

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/163770734/5d4709ab-9738-4ad7-a6c0-8b3270018bba)

![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/163770734/1094a0b9-39f7-4c05-96ff-d360acdd7751)

2024-07-09 17:23 UTC, dhairyagothi requested changes
![image](https://github.com/dhairyagothi/50_days_50_web_project/assets/142989448/ca1cbfbd-21b5-4e39-bf3f-3b56ef437ac3)


increase width to full and remove this contributor images

2024-07-09 18:08 UTC, DavidMarcosJ commented
Okay, I'll get to it.

2024-07-10 08:44 UTC, dhairyagothi requested changes

2024-07-10 08:44 UTC, dhairyagothi commented on public/index.html
> +                <p>SuhainaFathimaM</p></a>
remove contributor part

2024-07-10 15:53 UTC, dhairyagothi commented
good @DavidMarcosJ

2024-07-10 15:53 UTC, dhairyagothi commented
give email id to assign score

2024-07-10 17:18 UTC, DavidMarcosJ commented
davidmarcosj98@gmail.com

2024-07-11 03:30 UTC, merged

2024-07-11 12:20 UTC, dhairyagothi commented
Wrong email ID @DavidMarcosJ

2024-07-11 13:29 UTC, DavidMarcosJ commented
My mistake, I had the email in hidden, try again. Thanks @dhairyagothi

2024-07-11 15:30 UTC, dhairyagothi commented
![Uploading image.png…]()

email id not working

2024-07-11 16:54 UTC, DavidMarcosJ commented
I assume it is the same email as the github one because I am not registered anywhere called vSoC Manager or something like that.

2024-07-12 03:33 UTC, dhairyagothi commented
> I assume it is the same email as the github one because I am not registered anywhere called vSoC Manager or something like that.

are you a participant in Vsoc ?

2024-07-12 12:23 UTC, DavidMarcosJ commented
Nop

2024-07-12 12:24 UTC, DavidMarcosJ commented
> > I assume it is the same email as the github one because I am not registered anywhere called vSoC Manager or something like that.
> 
> are you a participant in Vsoc ?

No, how can I participate?

2024-07-13 08:30 UTC, dhairyagothi commented
> > > I assume it is the same email as the github one because I am not registered anywhere called vSoC Manager or something like that.
> > 
> > 
> > are you a participant in Vsoc ?
> 
> No, how can I participate?

it is over now but thanku for your contribution in my repo